apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: linstor-snapshot-test
spec:
  snapshotClassName: linstor-csi-snapshot-class
  source:
    name: linstor-pvc-test
    kind: PersistentVolumeClaim
